site_name: Diana Docs
repo_name: no-mole/diana-docs
repo_url: https://github.com/no-mole/diana-docs
theme:
  name: material
  language: zh
  features:
    - navigation.tabs

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - glightbox

nav:
- Index: index.md
- Getting started:
  - 什么是Diana: getting-started/什么是Diana.md
  - OAuth2.0: getting-started/OAuth2.0.md
  - OIDC: getting-started/OIDC.md
- 使用:
  - 快速开始: usage/quick-start.md
  - 应用: usage/应用.md
- 参考:
  - Shiro: reference/shiro.md
