site_name: Diama Docs
theme:
  name: material
  language: zh
  features:
    - navigation.tabs

nav:
- Index: index.md
- Getting started:
  - 什么是Diana: getting-started/什么是Diana.md
  - OAuth2.0: getting-started/OAuth2.0.md
  - OIDC: getting-started/OIDC.md
- 使用:
  - 快速开始: usage/quick-start.md
  